spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/db_uniceuma
spring.datasource.username=uniceuma
spring.datasource.password=uniceuma
spring.jpa.hibernate.ddl-auto=update